%% generated by soap from: /home/harshaka/workspace/erlang/temp/test_api/priv/www/example.wsdl
%% for service "contacts_service" and port "contacts_port"
%% using options: [{service,"contacts_service"},{port,"contacts_port"},{generate,both},{namespaces,[{"http://example.com/contacts.xsd",undefined}]},{generate_tests,both},{http_server,soap_server_mochiweb},{server_name,"example_server"},{http_client,soap_client_inets},{client_name,"example_client"},{strict,true}]

-module(example_server).

-include("test_api.hrl").
-include("example.hrl").

-export([store/3]).
-export([retrieve/3]).
-export([interface/0]).

-export([start/1]).

start(Options) ->
    soap:start_server(?MODULE, [Options]).

-spec store(Parsed_body::contact(),
    Soap_req::soap:soap_req(), State::soap:soap_handler_state())
    -> soap:soap_handler_response(id()).
store(_Parsed_body, Soap_req, State) ->
    %% your implementation goes here
    ?H("SOAP request: ~p", [Soap_req]),
    {ok, #id{}, Soap_req, State}.

-spec retrieve(Parsed_body::id(),
    Soap_req::soap:soap_req(), State::soap:soap_handler_state())
    -> soap:soap_handler_response(contact()).
retrieve(_Parsed_body, Soap_req, State) ->
    %% your implementation goes here
    ?H("SOAP request: ~p", [Soap_req]),
    Contact = #contact{first_name="Willem", last_name="de Jong", projects = ["soap", "xml"]},
    {ok, Contact, Soap_req, State}.

%% The 'interface()' function is used by the SOAP framework to access information about
%% the WSDL.
interface() ->
    ?INTERFACE.
