%% generated by soap from: /home/harshaka/workspace/erlang/temp/test_api/priv/www/example.wsdl
%% for service "contacts_service" and port "contacts_port"
%% using options: [{service,"contacts_service"},{port,"contacts_port"},{generate,both},{namespaces,[{"http://example.com/contacts.xsd",undefined}]},{generate_tests,both},{http_server,soap_server_mochiweb},{server_name,"example_server"},{http_client,soap_client_inets},{client_name,"example_client"},{strict,true}]

-module(example_client).

-include("example.hrl").

-export([interface/0]).

%% The functions that are described by the WSDL
-export([store/3]).
-export([retrieve/3]).

-spec store(Soap_body::contact(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response(id()).
store(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"store\"", interface()).

-spec retrieve(Soap_body::id(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response(contact()).
retrieve(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"retrieve\"", interface()).

%%% --------------------------------------------------------------------
%%% Internal functions
%%% --------------------------------------------------------------------
interface() ->
    ?INTERFACE.