%% generated by soap from: /home/harshaka/workspace/erlang/temp/test_api/priv/www/example.wsdl
%% for service "contacts_service" and port "contacts_port"
%% using options: [{service,"contacts_service"},{port,"contacts_port"},{test_values,true},{generate,both},{namespaces,[{"http://example.com/contacts.xsd",undefined}]},{generate_tests,both},{http_server,soap_server_mochiweb},{server_name,"example_server"},{http_client,soap_client_inets},{client_name,"example_client"},{strict,true}]

-module(example_server_test).

-include("example.hrl").

-export([store/3]).
-export([retrieve/3]).
-export([interface/0]).

-spec store(Parsed_body::contact(),
    Soap_req::soap:soap_req(), State::soap:soap_handler_state())
    -> soap:soap_handler_response(id()).
store(_Parsed_body, Soap_req, State) ->
    Result = 
        #id{
            id = 42},
    {ok, Result, Soap_req, State}.

-spec retrieve(Parsed_body::id(),
    Soap_req::soap:soap_req(), State::soap:soap_handler_state())
    -> soap:soap_handler_response(contact()).
retrieve(_Parsed_body, Soap_req, State) ->
    Result = 
        #contact{
            % Optional:
            id = 42,
            first_name = "?",
            last_name = "?",
            % List with zero or more elements:
            projects = ["?"]},
    {ok, Result, Soap_req, State}.

%% The 'interface()' function is used by the SOAP framework to access information about
%% the WSDL.
interface() ->
    ?INTERFACE.
